### ISSUE TITLE
BaseDao这个类好像没有包括在包里 

### ISSUE THREAD

**Issue by 8520Go** [yzcheng90/x_springboot-generator#2]
@yzcheng90  你好，BaseDao这个类好像没有包括在包里 

![1582863901(1)](https://user-images.githubusercontent.com/46882858/75510301-76b3b500-5a25-11ea-85d4-c944116de25a.png)

**Comment by yzcheng90** [comment]
新版本已经整合进去了，现在这个项目不用了
